# TOML Document

title = "TOML Document"

[Validator]
operatorAddr = "terravaloper1062zkmnlqhcpwsryk5kjf345x6njzzksqk9ljl"

[Feeder]
password = "qwer1234"

[APIs]
	[APIs.krw]
	coinone = "https://tb.coinone.co.kr/api/v1/tradehistory/recent/?market=krw&target=luna"

	[APIs.usd]
	dunamu = "https://quotation-api-cdn.dunamu.com/v1/forex/recent?codes=FRX.KRWUSD"

	[APIs.mnt]
	# API key is required
	# https://currencylayer.com/product
	currencylayer = "http://www.apilayer.net/api/live?access_key=f4f5c16e99a0f32baeab5be8ced1cd39"

	[APIs.sdr]
	imf = "https://www.imf.org/external/np/fin/data/rms_five.aspx?tsvflag=Y"

[Options]
interval = 200
