# TOML Document

title = "TOML Document"

[Validator]
operatorAddr = "terravaloper1rxawuuuatgwlwj7u59gxw7pnrp4dslgceup2rr"

[Feeder]
password = "Qlalfqjsgh#3"

[APIs]
	[APIs.krw]
	coinone = "https://tb.coinone.co.kr/api/v1/tradehistory/recent/?market=krw&target=luna"

	[APIs.usd]
	dunamu = "https://quotation-api-cdn.dunamu.com/v1/forex/recent?codes=FRX.KRWUSD"

	[APIs.mnt]
	# API key is required
	# https://currencylayer.com/product
	currencylayer = "http://www.apilayer.net/api/live?access_key="

	[APIs.sdr]
	imf = "https://www.imf.org/external/np/fin/data/rms_five.aspx?tsvflag=Y"

[Options]
interval = 30

	[Options.changeRateLimit]
	soft = 0.25
	hard = 0.5
